name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.WARGAME_DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wargame:latest
      - name: Trigger Jenkins Webhook (on Success)
        if: ${{ success() }} # 빌드가 성공한 경우에만 실행
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"status":"success"}' \
          https://9208-221-164-194-12.ngrok-free.app/github-webhook/